# include: package:pedantic/analysis_options.1.8.0.yaml

analyzer:
  exclude:
    - build/**
    - note.txt
    - ios/**

  strong-mode:
    implicit-casts: false

linter:
  rules:
    - annotate_overrides
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - constant_identifier_names
    - control_flow_in_finally
    - empty_statements